### ISSUE TITLE
Fix Source Control with xCode Project

### ISSUE THREAD

**Issue by Isaiaher** [HikerMobileApp/HikerApp#23]
Robin and I are the only ones that can compile to ios due to having macs. I created the initial Flutter project and it uses xCode to compile Dart to an ios app (may have some of that wrong but that is the flow of it) However, for some reason, Robin can no longer run my code on his Mac fo ios. Errors arise that we have tried to debug, but we believe it has to deal with our developer options in our xCode projects because it asks for a development team and Robin and I put ourselves because that is how we have always done it, but we may need an actual development team account? We will look into it. For now though, we may need to just do android, or just have me run the ios code for a little until we figure out what is really happening.

**Comment by RobinNaggi** [comment]
I think I found the problem I'll show you when I see you

**Comment by RobinNaggi** [comment]
We will talk about this in our next meeting, but i think we can close this.

**Comment by RobinNaggi** [comment]
After seeing that the project sometimes stops working when we make updates on different computers. We find that we can not change the ".project" class ion Xcode. There will be a warning when we run the project in Xcode but we have chosen to leave it because that will cause it to only work on your computer and stop working on the other team members.
