### ISSUE TITLE
(IOS) Change the logo 

### ISSUE THREAD

**Issue by RobinNaggi** [HikerMobileApp/HikerApp#27]
App logo is fine but we need to change the logo of when we go to close the app the flutter runner logo is still there

**Comment by Isaiaher** [comment]
Nice catch! I think this is because we need to set all the logos to the same thing I didn't want to go through the trouble of resizing the image 10 times for a temp logo
<img width="1278" alt="screen shot 2018-11-06 at 12 02 40 am" src="https://user-images.githubusercontent.com/40191651/48050709-81bf4380-e157-11e8-97ff-c992807cfeb3.png">

**Comment by RobinNaggi** [comment]
I have done this and merged it to master
